robot04:
  controller_manager:
    ros__parameters:
      update_rate: 10  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      base_controller:
        type: diff_drive_controller/DiffDriveController
  
  base_controller:
    ros__parameters:
      use_stamped_vel: false
      left_wheel_names: ["robot04_front_left_wheel_joint","robot04_back_left_wheel_joint"]
      right_wheel_names: ["robot04_front_right_wheel_joint","robot04_back_right_wheel_joint"]
  
      wheel_separation: 0.20
      wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
      wheel_radius: 0.06
  
      wheel_separation_multiplier: 1.0
      left_wheel_radius_multiplier: 1.0
      right_wheel_radius_multiplier: 1.0
  
      odom_frame_id: robot04_odom
      base_frame_id: robot04_base_link
      pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  
      position_feedback: false
      open_loop: true
      enable_odom_tf: false
  
      cmd_vel_timeout: 0.5 # seconds
      publish_limited_velocity: true
      velocity_rolling_window_size: 10
  
      linear.x.has_velocity_limits: false
      linear.x.has_acceleration_limits: false
      linear.x.has_jerk_limits: false
      linear.x.max_velocity: 0.0
      linear.x.min_velocity: 0.0
      linear.x.max_acceleration: 0.0
      linear.x.max_jerk: 0.0
      linear.x.min_jerk: 0.0
  
      angular.z.has_velocity_limits: false
      angular.z.has_acceleration_limits: false
      angular.z.has_jerk_limits: false
      angular.z.max_velocity: 0.0
      angular.z.min_velocity: 0.0
      angular.z.max_acceleration: 0.0
      angular.z.min_acceleration: 0.0
      angular.z.max_jerk: 0.0
      angular.z.min_jerk: 0.0